---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add an apt key by id from a keyserver
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927

    - name: Create file with content
      copy:
        content: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
        dest: /etc/apt/sources.list.d/mongodb-org-3.2.list

    - name: Update repositories cache and install mongodb-org package
      apt:
        name: mongodb-org
        update_cache: yes

    - name: enable service mongod
      systemd:
        name: mongod
        enabled: yes